"""
generate.py — Stage 4 of the UF Dining Unofficial Guide RAG pipeline.

  retrieved chunks  →  Groq LLM  →  grounded answer + sources
  ───────────────     ─────────     ──────────────────────────
  from embed.py       llama-3.3-70b-versatile (free tier)

Grounding design (read this before changing the prompt):
- The system prompt FORBIDS the model from using outside knowledge.
  "only" and "do not use any outside knowledge" are load-bearing words.
- Source attribution is appended PROGRAMMATICALLY after generation —
  we do not trust the LLM to cite sources reliably on its own.
- If the retrieved chunks don't contain the answer, the model is
  instructed to say so explicitly rather than hallucinate.
"""

from __future__ import annotations

import os
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

# ── Config ──────────────────────────────────────────────────────────────────────
GROQ_MODEL = "llama-3.3-70b-versatile"   # free tier, no credit card required
MAX_TOKENS = 512


# ── Client (lazy init so importing this module doesn't fail without a key) ──────
_client: Groq | None = None

def _get_client() -> Groq:
    global _client
    if _client is None:
        api_key = os.getenv("GROQ_API_KEY")
        if not api_key:
            raise EnvironmentError(
                "GROQ_API_KEY not set. Copy .env.example to .env and add your key."
            )
        _client = Groq(api_key=api_key)
    return _client


# ── Prompt template ─────────────────────────────────────────────────────────────
SYSTEM_PROMPT = """\
You are an expert on University of Florida campus dining.
Answer the user's question using ONLY the information in the provided documents.
Do not use any outside knowledge, general assumptions, or information not present \
in the documents below.
If the documents do not contain enough information to answer the question, respond \
with exactly: "I don't have enough information on that."
Be concise and direct. Do not repeat the question.\
"""

def _build_context(chunks: list[dict]) -> str:
    """
    Format retrieved chunks into the user message.

    Each chunk is labelled with its source title and index so the model
    can reference them, but we do NOT ask the model to cite — we append
    sources programmatically instead (see generate_answer).
    """
    parts = []
    for i, chunk in enumerate(chunks, 1):
        parts.append(
            f"[Document {i} — {chunk['source_title']}]\n{chunk['text'].strip()}"
        )
    return "\n\n".join(parts)


# ── Generation ──────────────────────────────────────────────────────────────────
def generate_answer(question: str, chunks: list[dict]) -> dict:
    """
    Generate a grounded answer from the retrieved chunks.

    Args:
        question: the user's raw query string
        chunks:   list of dicts returned by embed.retrieve()
                  (each has text, source_title, source_url, score)

    Returns a dict with:
        answer   — LLM response text (grounded to chunks only)
        sources  — deduplicated list of {"title": ..., "url": ...}
                   appended programmatically, not generated by the LLM
        chunks   — the raw chunks used (for debugging / display)
    """
    context = _build_context(chunks)

    user_message = (
        f"Documents:\n{context}\n\n"
        f"Question: {question}"
    )

    response = _get_client().chat.completions.create(
        model=GROQ_MODEL,
        max_tokens=MAX_TOKENS,
        temperature=0.2,       # low temp = more faithful to context, less creative
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user",   "content": user_message},
        ],
    )

    answer = response.choices[0].message.content.strip()

    # ── Programmatic source attribution ─────────────────────────────────────────
    # Deduplicate by URL so the same source isn't listed twice if multiple
    # chunks came from it. Order preserved (most relevant chunk = first).
    seen_urls: set[str] = set()
    sources: list[dict] = []
    for chunk in chunks:
        url = chunk["source_url"]
        if url not in seen_urls:
            seen_urls.add(url)
            sources.append({
                "title": chunk["source_title"],
                "url":   url,
                "score": chunk["score"],
            })

    return {
        "answer":  answer,
        "sources": sources,
        "chunks":  chunks,
    }


# ── Quick CLI test ───────────────────────────────────────────────────────────────
if __name__ == "__main__":
    from embed import retrieve

    question = "What happens to unused flex dollars at the end of the spring semester?"
    print(f"Question: {question}\n")

    chunks = retrieve(question)
    result = generate_answer(question, chunks)

    print(f"Answer:\n{result['answer']}\n")
    print("Sources:")
    for s in result["sources"]:
        print(f"  [{s['score']}] {s['title']}")
        print(f"           {s['url']}")
